# Generated by Django 3.2.4 on 2021-06-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210621_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(blank=True, default='What ill do : \nExperience : \nPrice : ', max_length=2000, null=True),
        ),
    ]
