# Generated by Django 3.2.4 on 2021-06-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default='img/brand/1.png', upload_to='jobs/'),
        ),
    ]
