# Generated by Django 3.2.4 on 2021-06-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='img/default.png', upload_to='jobs/'),
        ),
    ]
