# Generated by Django 3.2.4 on 2021-06-22 21:20

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_job_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(default='jobs/default.jpg', upload_to=jobs.models.image_upload),
        ),
    ]
