# Generated by Django 3.2.4 on 2021-06-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_job_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('website', models.URLField()),
                ('cv', models.FileField(upload_to='apply')),
                ('conver_letter', models.TextField(max_length=1000)),
            ],
        ),
    ]
