# Generated by Django 3.2.4 on 2021-06-23 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_applying'),
    ]

    operations = [
        migrations.AddField(
            model_name='applying',
            name='job',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='apply_job', to='jobs.job'),
            preserve_default=False,
        ),
    ]
