# Generated by Django 3.2.4 on 2021-06-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_applying_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='applying',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
