# Generated by Django 3.2.4 on 2021-06-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_applying_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applying',
            old_name='conver_letter',
            new_name='cover_letter',
        ),
    ]
