# Generated by Django 3.2.4 on 2021-06-23 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0016_rename_conver_letter_applying_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_poster', to='auth.user'),
            preserve_default=False,
        ),
    ]
