# Generated by Django 3.2.4 on 2021-06-26 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-date_posted',)},
        ),
    ]
