# Generated by Django 3.2.4 on 2021-06-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='job',
        ),
    ]
