# Generated by Django 3.2.4 on 2021-07-02 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_alter_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='jobs.job'),
        ),
    ]
