# Generated by Django 3.2.4 on 2021-07-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_alter_comment_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
