# Generated by Django 3.2.4 on 2021-07-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20210702_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slug',
        ),
    ]
